name: Vita.lk daily scan

on:
  
  repository_dispatch:
    types: [trigger_scan]
  
  workflow_dispatch:
 
  schedule:
    - cron: '*/20 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    env:
      TZ: 'Asia/Colombo' 
      SCAN_MODE: "production"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
         
          
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push Data to Main Branch
        run: |
          # Configure Git Bot
          git config --global user.name "Vita.lk Bot"
          git config --global user.email "bot@vita.lk"
          
          # Stage the new/modified data files in the 'data' folder
          git add data/*.csv
          
          # Commit the changes. '|| echo' prevents failure if no files changed.
          # The commit will happen on the checked-out 'main' branch
          git commit -m "DATA UPDATE: $(date)" || echo "No changes to commit"
          
          # Push the changes to the current branch ('main')
          git push origin main
